# Generated by Django 4.0.5 on 2022-06-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=15)),
                ('description', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('text_title', models.CharField(max_length=100)),
                ('text_text', models.CharField(max_length=500)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('Time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
