# Generated by Django 4.0.5 on 2022-06-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zns_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
